target_sources(${PROJECT_NAME} PRIVATE	BatchRenderer.h
										BatchRenderer.cpp
										Bindable.h
										Camera.h
										Camera.cpp
										Graphics.h
										Graphics.cpp
										Shader.h
										Shader.cpp
										Stats.h
										Stats.cpp
										Texture2D.h
										Texture2D.cpp
										Vertex.h
										Viewport.h
										Viewport.cpp
										)

#add_subdirectory(UI)